version: "3"

name: attendance-system
services:
  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432

  server:
    image: app-base:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    depends_on:
      - database
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: ${NODE_ENV}
      SESSION_SECRET: ${SESSION_SECRET}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - ${SERVER_PORT}:3000
    command: /bin/sh -c "pnpm nx run server:start"
    volumes:
      - main_modules:/app/node_modules
      - ./services/server:/app/services/server

  dashboard:
    image: dashboard:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dashboard
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    ports:
      - ${DASHBOARD_PORT}:4001
    command: /bin/sh -c "pnpm nx run dashboard:start"

  seed:
    image: seed:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: seed
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TOTAL_SCHOOLS: ${TOTAL_SCHOOLS}
      TOTAL_STUDENTS_PER_SCHOOL: ${TOTAL_STUDENTS_PER_SCHOOL}
    command: /bin/sh -c "pnpm nx run dashboard:start"

networks:
  default:
    name: attendance-system

volumes:
  main_modules: {}
